### ISSUE TITLE
I get a continuous error on console F8 when I die

### ISSUE THREAD

**Issue by SATTAGAMES** [TheIndra55/fivem-burglary#2]
I get a continuous error on console F8 when I die
Could you help me with this error?
The job is running fine off this error in the console

http://prntscr.com/njm95q

**Comment by TheIndra55** [comment]
Couldn't reproduce this on a local server, might need to test with more people for this

**Comment by tymaan** [comment]
Getting the same console error. Losing about 16fps from resource warning whenever you die

**Comment by tymaan** [comment]
`		-- cancel mission if player is dead
		if IsPedDeadOrDying(PlayerPedId()) and onMission then
			TriggerServerEvent("burglary:ended", true, false)
			
			ForceEndMission()
		end`



gameplay/busted.lua    this solves that issua

**Comment by TheIndra55** [comment]
Thanks @tymaan i'll look into it later today

**Comment by TheIndra55** [comment]
Fixed as of #6
