### ISSUE TITLE
Request for update ?

### ISSUE THREAD

**Issue by DevDokus** [TheIndra55/fivem-burglary#9]
I like this mod but there is one thing that i really do dislike. 
You robbed a few houses successful and you have the van 
full with items, if one of the burglaries goes wrong, you also 
lose all items in the van from all successful burglaries.
That is really to bad, i hope this can be changed later.

**Comment by TheIndra55** [comment]
I see, I will look into 'redesigning' the bust/caught system when I have some time.

**Comment by DVTGroup** [comment]
> I like this mod but there is one thing that i really do dislike.
> You robbed a few houses successful and you have the van
> full with items, if one of the burglaries goes wrong, you also
> lose all items in the van from all successful burglaries.
> That is really to bad, i hope this can be changed later.

I’d say in the mean time, you can try to save the items after each successful burglary and just keep stacking up the list of grabbed items. After the mission, it still calculates the worth and how it would normally do it. 
So basically what you can do is:
- Save items, keep stacking / adding to a list, once the burglary fails you can call the sell items event to give the player still the money

- Give the items to the players after each successful burglary and make a “total sale” at the end. With scanning the inventory and picking out the right items, calculating the worth and sell it

I can try to see if I can get it to work tomorrow.
